### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by johnfelipe** [rlafuente/scraper-iniciativas#2]
@rlafuente do u have time for a pay job scrapping and parsing

**Comment by rlafuente** [comment]
I've emailed you about this, let me know if you got it.

**Comment by johnfelipe** [comment]
I answer pls check

**Comment by johnfelipe** [comment]
Do u see my answer?

**Comment by johnfelipe** [comment]
Hi again, pls tell me do u see my answer
